version: '3.7'
services:
  web:
    build:
      context: ./src
      dockerfile: ../aspnetcore2_2.dockerfile
      args:
        project: Sample.App.Web
        configuration: Debug
    container_name: web
    ports:
      - 80:80
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_MONITORING_ENABLED=true
    depends_on:
      - elasticsearch
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
    - 3000:3000
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=secret
    - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
    - type: bind
      source: ./grafana/config.ini
      target: /etc/grafana/config.ini
    - type: bind
      source: ./grafana/provisioning
      target: /etc/grafana/provisioning
    depends_on:
    - prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - web
    - cadvisor
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
volumes:
  elasticsearch-data: